version: '3.9'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:123456@db/postgres
    ports:
      - "8000:8000"
    volumes:
      - /tmp/uploads/:/tmp/uploads
    networks:
      - app_network

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app_network
    
  player:
    build: ./player_service
    depends_on:
      - backend
    ports:
      - "8001:8001"
    networks:
      - app_network

  sounds:
    build: ./sounds_execution_service
    depends_on:
      - player
    ports:
      - "50051:50051"
    volumes:
      - /tmp/uploads/:/tmp/uploads
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge

