# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: player.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'player.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cplayer.proto\x12\x06player\"-\n\x0c\x41udioRequest\x12\x10\n\x08\x61udio_id\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\"\x1f\n\x0cPlayResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1f\n\x0cStopResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x0e\n\x0c\x45mptyRequest2\x81\x01\n\rPlayerService\x12\x37\n\tPlayAudio\x12\x14.player.AudioRequest\x1a\x14.player.PlayResponse\x12\x37\n\tStopAudio\x12\x14.player.EmptyRequest\x1a\x14.player.StopResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'player_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOREQUEST']._serialized_start=24
  _globals['_AUDIOREQUEST']._serialized_end=69
  _globals['_PLAYRESPONSE']._serialized_start=71
  _globals['_PLAYRESPONSE']._serialized_end=102
  _globals['_STOPRESPONSE']._serialized_start=104
  _globals['_STOPRESPONSE']._serialized_end=135
  _globals['_EMPTYREQUEST']._serialized_start=137
  _globals['_EMPTYREQUEST']._serialized_end=151
  _globals['_PLAYERSERVICE']._serialized_start=154
  _globals['_PLAYERSERVICE']._serialized_end=283
# @@protoc_insertion_point(module_scope)
